stages:
    - build
    - deploy
image: moreillon/tdd-dind
services:
    - name: docker:19.03.12-dind

variables:
    APPLICATION_NAME: polygonal-annotation-tool
    CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}
    CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}
    K8S_NAMESPACE: no-code-ai

build:
    stage: build
    only:
        - tags
    tags:
        - dind
    before_script:
        # Registry login
        - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_PUBLIC_URL}
        # Create repository in ECR if it does not exist yet
        - >
            aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME}
            || echo "Repository might have already existed"
    script:
        # Building image
        - docker build -t ${CONTAINER_IMAGE} .
        # Tagging images
        - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
        # Pushing images
        - docker push ${CONTAINER_IMAGE}
        - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  only:
    - tags
  tags:
    - internal
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: onpremise
    kubernetes:
      namespace: ${K8S_NAMESPACE}