
variables:
  APPLICATION_NAME: annotation-tool-polygon
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  SERVICE_PORT: 31226

build:
  stage: build
  tags:
    - x86
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE}
