apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_LABELS
          value: NG,makure,kizu,ketuniku,arabiki,usui,hagare,tare,yuzu,butu,test1,test2
        - name: VUE_APP_STORAGE_SERVICE_API_URL
          value: http://172.16.116.51:31221
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
    nodePort: ${SERVICE_PORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
