apiVersion: apps/v1
kind: Deployment
metadata:
    name: polygonal-annotation-tool
spec:
    replicas: 1
    selector:
        matchLabels:
            app: polygonal-annotation-tool
    template:
        metadata:
            labels:
                app: polygonal-annotation-tool
        spec:
            containers:
                - name: polygonal-annotation-tool
                  image: ${CONTAINER_IMAGE_TAGGED}
                  env:
                      - name: VUE_APP_STORAGE_SERVICE_API_URL
                        value: http://172.16.98.151:30480/api
                      - name: VUE_APP_ANNOTATION_FIELD
                        value: polygonalAnnotation
                      - name: VUE_APP_LABELS
                        value: example
                      - name: VUE_APP_DEFAULT_LABEL
                        value: example
                  ports:
                      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: polygonal-annotation-tool
spec:
    ports:
        - port: 80
          nodePort: 30444
    selector:
        app: polygonal-annotation-tool
    type: NodePort
